cache: bundler
language: ruby
rvm:
  - 2.4.3
  - 2.5.0
  - ruby-head

gemfile:
  - gemfiles/rails_5.0.gemfile
  - gemfiles/rails_5.1.gemfile
  - gemfiles/rails_5.2.gemfile

matrix:
  fast_finish: true
  allow_failures:
    - rvm: ruby-head
